"""
Page data extracted from The Book of the Distinguished Gentlemen.
Each page has: number, image filename, title, and transcription lines.
"""

PAGES = [
    {
        "number": 1,
        "image": "IMG_3985.jpg",
        "title": "The Title Page",
        "transcription": [
            '"THE BOOK"',
            "(Three underlining bars)",
            "",
            "THE DISTINGUISHED GENTLEMEN",
            "EST 2022",
            "D/G",
        ],
    },
    {
        "number": 2,
        "image": "IMG_3986.jpg",
        "title": "The Roster & Table of Contents",
        "transcription": [
            "THE DISTINGUISHED GENTLEMEN",
            "",
            'CPT Wesley Pritchett \u2014 "Mr. Green"',
            'Dr. Ryan Cudahy \u2014 "Mr. White"',
            'Mr. John Molinari \u2014 "Mr. Pink"',
            'Esq. Nicholas Deming \u2014 "Mr. Black"',
            'Mr. Brian Cook \u2014 "Mr. Orange"',
            'Mr. Justin Rothaug \u2014 "Mr. Brown"',
            'Mr. Anthony Clifford \u2014 "Mr. Blue"',
            'Mr. Evan Hewitt \u2014 "Mr. Purple"',
            "",
            "TABLE of CONTENTS",
            "Mission, General Etiquette + Values",
            "New DG Additions",
            "By-laws + Customs",
            "Monthly Dinner By-laws + Customs",
            "Dinner Re-caps (Time, place, outcome, Quotes etc.)",
            "Memorable Moments",
        ],
    },
    {
        "number": 3,
        "image": "IMG_3987.jpg",
        "title": "Founding Members & Philosophy",
        "transcription": [
            "Mr. Brian Cook \u2014 Founding Member",
            "Mr. Anthony Clifford \u2014 Q1 C423 Member",
            "Dr. Ryan Cudahy \u2014 Founding Member",
            "Nicholas Deming, Esq \u2014 Founding Member",
            "Mr. John Molinari \u2014 Founding Member",
            "CPT Wesley Pritchett \u2014 Founding Member / President",
            "Mr. Justin Rothaug \u2014 Founding Member",
            "Mr. Evan Hewitt \u2014 Q2 C423 Member",
            "",
            '\u201cA Gentleman is one who puts more into the world than he takes out\u201d \u2014 G.B. Shaw',
        ],
    },
    {
        "number": 4,
        "image": "IMG_3988.jpg",
        "title": "Roles & Core Values",
        "transcription": [
            "EXPLANATION OF ROLES",
            "",
            "Distinguished Gentleman: Rotating member selected monthly \u2014 Responsible for coordinating the monthly dinner. Steward of the BOOK.",
            "President: Responsible for overall oversight of the DG program.",
            "Squire: Responsible for maintaining the by-laws and arbitrating/making final judgements on grievances \u2014 as well as keeping track of any rulings to ensure accountability.",
            "Social Chair: Coordinating informal social events for members throughout the month for DGs + prospective members.",
            "Tapping Member: Communicates social events with prospective members + coordinating details for the first dinner with a newly selected member.",
            "",
            "1 | MISSION, ETIQUETTE AND VALUES",
            "A group of gentleman whose goal is to create a brotherhood with the foundation built on friendship, loyalty and collective improvement.",
            "",
            "Foster Lifelong Friendship: Strengthen bonds with each other. Be present.",
            "Loyalty: Be trustworthy and hold yourself accountable. Live with honesty and morality.",
            "Collective Improvement: Support each other in our personal and professional endeavors. Help each other for the sake of it.",
            "",
            "We take this SERIOUSLY (But not too seriously)",
        ],
    },
    {
        "number": 5,
        "image": "IMG_3989.jpg",
        "title": "Recruitment Protocols",
        "transcription": [
            "2 | NEW DG ADDITIONS",
            "",
            "New DG Members are to be tapped by current members for demonstrating presence, leadership and character. They should add value to the DG group and enhance our collective growth.",
            "",
            "We do not talk openly about this group \u2014 we remain humble and seek to improve our collective professionalism.",
            "",
            "We aim to add no more than 1 member / quarter. There is no requirement to add a member/quarter if there is no consensus reached on an addition.",
            "",
            "The DG group should not grow to more than 12 members, unless voted to change by unanimous vote.",
        ],
    },
    {
        "number": 6,
        "image": "IMG_3990.jpg",
        "title": "Nominations & By-Laws",
        "transcription": [
            "4. Nominations are to be surfaced to the group during the monthly dinner sessions. The nominee should be known by all members \u2014 it is the nominating member\u2019s responsibility to socialize the nominee.",
            "",
            "3 | DG BY-LAWS AND CUSTOMS",
            "These are high-level, general by-laws and customs. The by-laws, customs and etiquette surrounding the monthly dinner events are in Section 4.",
            "",
            "Members should do their best to attend monthly social events, although not mandatory.",
            "Members should take care to be responsive in the group text and email threads.",
            "Members must make timely repayments of any debts/redemptions \u2014 within 24 hours of receipt.",
            "Members should be early and communicate their availability for the monthly dinner \u2014 ensuring the DG has adequate planning time.",
            "If a DG misses the pre-dinner drinks, he shall buy the first TWO rounds after dinner.",
            "All DGs should read this charter and be familiar with all the by-laws, customs and the poem.",
            "DGs must make a minimum of 1 dinner/quarter.",
            "Violations of by-laws and this charter as found by the ESQ (Esq. Nicholas Deming) shall result in the DG being labeled a \u201cDEGENERATE\u201d until found in good standing by the other DGs.",
        ],
    },
    {
        "number": 7,
        "image": "IMG_3992.jpg",
        "title": "Challenge Coin & Monthly Dinner By-Laws",
        "transcription": [
            "9. The Challenge Coin",
            "a. The coin is a token representing the DG Brotherhood and a sign of membership.",
            "b. All DGs MUST have the coin on them at the DG dinners or they will suffer punishment.",
            "",
            "4 | MONTHLY DINNER BY-LAWS AND CUSTOMS",
            "These are high-level, general by-laws and customs and etiquette for the dinner events themselves.",
            "",
            "Distinguished Gentleman Responsibilities:",
            "",
            "Scheduling and Coordination",
            "a. Send out the dinner availability tracker on or around the 15th of the month prior to the dinner to be scheduled.",
            "b. Select an evening that works for all members \u2014 if multiple evenings are available, the members will vote on which is preferred.",
            "",
            "Venue Selection",
            "a. Select a venue commensurate of the occasion. We prefer traditional venues, i.e., steakhouses, where volume and rowdy conversation is encouraged!",
            "b. The venue should be within walking distance of each other when possible.",
            "",
            "Invitation and Communication",
            "a. An invitation highlighting the location, time, and theme, as well as any other requirements, should be sent out at the start of the month.",
        ],
    },
    {
        "number": 8,
        "image": "IMG_3993.jpg",
        "title": "Dinner Logistics & Etiquette",
        "transcription": [
            "This should be followed up with a Google Calendar invite holding the event w/ details.",
            "b. The DG is responsible for ensuring all the details around the dinner event are understood.",
            "",
            "Host (DG) Responsibilities",
            "a. Ensure that the first round is ordered at the pre-dinner location.",
            "b. Ensure that the evening goes off seamlessly by handling all logistics coordination with the restaurants, Ubers, etc.",
            "c. Pay for the dinner on one tab. (Capture the evening on the disposable camera).",
            "",
            "Post-Dinner Responsibilities",
            "a. Ensure that the tab for the evening is sent out to members as soon as reasonably possible.",
            "b. Get that disposable camera developed ASAP.",
            "",
            "Event By-Laws and Customs",
            "",
            "Etiquette",
            "a. Dress Code: At the monthly dinners, the dress code is as follows: suits at a minimum (ties optional). No jeans or sneakers (unless by specific exception).",
            "",
            "Pre-Dinner Drinks/Activities",
            "a. Should start around 6PM \u2014 the DG should be the first to arrive and have the first round of cocktails ready.",
            "b. The location should be within walking distance of the selected restaurant.",
            "c. The DG orders the first round of drinks.",
            "d. If there is a new member, they should have 3-5 minutes to give an introduction.",
            "e. If a DG misses the pre-dinner drinks, he shall buy the first 2 rounds after dinner.",
        ],
    },
    {
        "number": 9,
        "image": "IMG_3994.jpg",
        "title": "Dinner Flow & Run of Show",
        "transcription": [
            "3. Dinner",
            "a. The DG is responsible to ensure the reservation is set and we are seated in a timely manner.",
            "",
            "Post-Dinner Drinks/Activities",
            "a. Following dinner \u2014 the night is open. We will head to the next venue selected by the DG. No formal commitments or requirements exist from here on out!",
            "",
            "5 | DG DINNER RUN OF SHOW",
            "NO PHONES at DINNER!!!",
            "",
            "Introduction: The DG is responsible for giving an introductory toast \u2014 and gives insight as to why the venue was selected.",
            "a. The DG will give an overview to all members of the run of show for the evening and any special additions.",
            "",
            "Successes, Trials and Promotions:",
            "a. Each Gentleman is encouraged to share any developments in their personal or professional lives. We will toast to these.",
            "b. Additionally \u2014 if there are any challenges or opportunities to support each other \u2014 this is the time we will discuss these opportunities or challenges.",
            "",
            "Prospective Member Discussion",
            "a. A member has 30 seconds to suggest a member addition \u2014 the group then votes yes or no on whether to hear the proposal...",
        ],
    },
    {
        "number": 10,
        "image": "IMG_3995.jpg",
        "title": "Voting & Airing of Grievances",
        "transcription": [
            "...hear the proposal. Only a majority of votes are needed to hear the proposal.",
            "b. If the majority is reached, each member has 30 seconds to make a case for or against.",
            "c. Once each member has spoken \u2014 the vote is requested.",
            "d. ALL MEMBERS must vote and ALL MEMBERS must accept the proposal (Unanimous).",
            "e. IF there is a vote against \u2014 the parties voting against and the proposer have 7 days to question.",
            "f. IF a proposal is accepted \u2014 the member that suggested the nominee must present the invitation.",
            "Note: If a nominee cannot make the dinner, they are deferred to the next month.",
            "",
            "6 | AIRING of GRIEVANCES",
            "a. Never personal, always jolly.",
            "b. ESQ (Nicholas Deming) is the arbitrator and final judge for all grievances and thereby rulings.",
            "c. The airing airer has 30 seconds to state the grievance, the defendant has 30 seconds to make the counter argument.",
            "d. The ESQ then opens the floor to other members to provide evidence, then makes a summary ruling and deals the sentence.",
            "e. Once a grievance has been aired \u2014 it cannot be aired at following dinners \u2014 unless a resolution was not reached.",
            "f. The newest DG member can have a grievance brought against him at his initial dinner but cannot respond.",
        ],
    },
    {
        "number": 11,
        "image": "IMG_3996.jpg",
        "title": "Closing & DG I Recap",
        "transcription": [
            "5) Closing",
            "The DG is responsible for giving a closing toast, shares who the next DG will be, and ensures all members know where the post-dinner location is.",
            "Note: Pay the tab and ensure the receipt is documented.",
            "",
            "\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500",
            "",
            "5) DINNER RECAPS",
            "",
            "DG I \u2014 FESTIVUS!",
            "DG: CPT Pritchett",
            "Date: 12/14/22",
            "Locations: Greens (Ft. Mason) \u2192 Maybeck\u2019s \u2192 Balboa Cafe",
            "S/T/P: [Short / Tall / Personal]",
            "PM: Anthony Clifford voted in",
            "Grievances: The Tenderloin Uber abandonment \u2014 Mr. Molinari GUILTY",
        ],
    },
    {
        "number": 12,
        "image": "IMG_3997.jpg",
        "title": "DG II & DG III Recaps",
        "transcription": [
            "DG II",
            "DG: Mr. Brian Cook",
            "Date: 1/24/23",
            "Locations: The Devil\u2019s Acre \u2192 Original Joe\u2019s \u2192 Gino and Carlo",
            "S/T/P: N/A",
            "PM: N/A",
            "Grievances: N/A",
            "Notes: DG Charter written. Mr. Clifford\u2019s first event.",
            "",
            "\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500",
            "",
            "DG III",
            "DG: Dr. Ryan Cudahy",
            "Date: 2/21/23",
            "Locations: Harper and Rye \u2192 Harris\u2019 (The Steakhouse) \u2192 Tupelo",
            "S/T/P: Mr. Rothaug + Mr. Cook Promotions. Mr. Clifford Job Promotions.",
            "PM: N/A",
            "Grievances: HOPR Failure \u2014 Cudahy (Failed attempt to get into House of Prime Rib).",
            "Notes: DG Charter adoption \u2014 talking about group.",
        ],
    },
    {
        "number": 13,
        "image": "IMG_3998.jpg",
        "title": "DG IV & DG V Recaps",
        "transcription": [
            "DG IV",
            "DG: ESQ Deming",
            "Date: 3/30/23",
            "Locations: Black Magic Voodoo Lounge \u2192 Bobo\u2019s \u2192 Silver Cloud",
            "S/T/P: Mr. Rothaug weight loss / fitness journey (4 months). March Madness. Mr. Clifford wedding venue selection.",
            "PM: N/A",
            "Grievances: Cudahy not reading charter.",
            "Notes: Charter: Add 3 nomination counts. Add \u201cNever personal, always jolly\u201d grievance rule.",
            "",
            "\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500",
            "",
            "DG V",
            "DG: Mr. Molinari",
            "Date: 4/21/23",
            "Locations: Geelou (The Marina spot) \u2192 Izzy\u2019s \u2192 Balboa Cafe",
            "S/T/P: Mr. Clifford excelling at quota / merit. Dr. Cudahy exceeding productivity goals.",
            "PM: Discussed Mr. Evan Hewitt and Mr. Mario Halten \u2192 Members meet.",
            "Grievances: N/A",
        ],
    },
    {
        "number": 14,
        "image": "IMG_3999.jpg",
        "title": "DG VI & DG VII Recaps",
        "transcription": [
            "DG VI",
            "DG: Mr. Rothaug",
            "Date: 5/19/23",
            "Locations: Amado\u2019s \u2192 Lolinda \u2192 Emporium",
            "S/T/P: \u2014",
            "PM: \u2014",
            "Grievances: \u2014",
            "Notes: CPT Pritchett absent. Gifts for CPT Pritchett.",
            "",
            "\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500",
            "",
            "DG VII",
            "DG: Mr. Clifford",
            "Date: 6/29/23",
            "Locations: Balboa \u2192 Cote Ouest Bistro \u2192 Final Final",
            "S/T/P: Mr. Rothaug / Hewitt / ESQ Deming Birthdays",
            "PM: N/A",
            "Grievances: \u2014",
            "Notes: Mr. Hewitt\u2019s first dinner.",
        ],
    },
    {
        "number": 15,
        "image": "IMG_4001.jpg",
        "title": "DG VIII & DG IX Recaps",
        "transcription": [
            "DG VIII",
            "DG: Mr. Cook",
            "Date: 8/22/23",
            "Locations: Cook\u2019s House \u2192 Bar Bocce \u2192 Salito\u2019s Crab House \u2192 Final Final",
            "S/T/P: ESQ Deming Partner promotion. Mr. Molinari on finding BAE. Positive health news for Mr. Clifford\u2019s grandmother. Dr. Cudahy\u2019s new nephew.",
            "PM: Dr. Cudahy mentions Mr. Phil Rose and Mr. Austin Estrada \u2014 no vote.",
            "Grievances: Mr. Purple (Evan) to review charter.",
            "Notes: Book discussion.",
            "",
            "\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500",
            "",
            "DG IX",
            "DG: Dr. Cudahy",
            "Date: 9/26/23",
            "Locations: The Ramp \u2192 Palm Court at RH \u2192 Tupelo",
            "S/T/P: \u2014",
            "Grievances: \u2014",
            "Notes: Goals + Accountability. CPT Pritchett absent.",
        ],
    },
    {
        "number": 16,
        "image": "IMG_4002.jpg",
        "title": "DG X & DG Wedding",
        "transcription": [
            "DG X",
            "DG: ESQ Nick Deming",
            "Date: 10/25/23",
            "Locations: Old Ship Saloon \u2192 Pierside \u2192 Northstar (Cafe)",
            "S/T/P: \u2014",
            "PM: \u2014",
            "Grievances: Nick\u2019s vulnerabilities.",
            "",
            "\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500",
            "",
            "DG WEDDING!",
            "DG: Mr. Anthony Clifford",
            "Date: 11/4",
            "Locations: Perry\u2019s \u2192 Mauna Loa \u2192 Saint Philip the Apostle \u2192 The Peaks \u2192 Olympic Club \u2192 Bed",
            'Text: "If I could turn back time..."',
            "Notes: + Mr. Clifford Birthday Month.",
        ],
    },
    {
        "number": 17,
        "image": "IMG_4003.jpg",
        "title": "DG XI \u2014 FESTIVUS II (DG Turns 1!)",
        "transcription": [
            "DG XI // FESTIVUS II (DG Turns 1!)",
            "DG: Mr. Molinari",
            "Date: 12/19/23",
            "Locations: Elements Bar + Lounge \u2192 John\u2019s Grill \u2192 Balboa",
            "",
            "Charter Review: [Mission/Goals/Etiquette/Monthly Donation]",
            "Cadence: Monthly voted to keep. Miss absence case by case.",
            "Roles: Responsibility DG President: remains.",
            "Trip: Spring Training \u2192 Mar 1/2.",
            "GOAL: Yearly Goal \u2192 Spreadsheet",
            "",
            "S/T/P:",
            "JR \u2192 single",
            "AC \u2192 married",
            "Dr. Ryan \u2192 medical/contract targets",
            "PM: N/A",
            "",
            "Grievance of the Year!",
            "",
            "Grievances of the Year \u201923:",
            "Cook disappearing \u2014 kidnapped by Lucy \u2014 Cudahy",
            "Molinari stranding DGs in the TL (Tenderloin) \u2014 CPT Pritchett (3 votes)",
            "Cudahy \u2018HOPR Shanghai\u2019 (House of Prime Rib) \u2014 CPT Pritchett",
            "Cook forgetting how to text \u2014 Cudahy (3 votes)",
            "Secret Santa to close.",
            "Notes: Cudahy Cleaner. Purple (Evan) Absent. +1 dinner mentioned.",
        ],
    },
    {
        "number": 18,
        "image": "IMG_4004.jpg",
        "title": "DG Survey Results",
        "transcription": [
            "DG Survey",
            "",
            "Q1 DG Mission:",
            "25% \u2192 Bad",
            "Event \u2192 57.1%",
            "Activity \u2192 14.3%",
            "",
            "Q2 Alignment Trip:",
            "Tahoe \u2192 14.3%",
            "Nature \u2192 42.9% \u2192 Anthony Clifford",
            "Spring \u2192 42.9%",
            "",
            "Q3 +1 Dinner:",
            "Yes \u2192 28.6%",
            "Yes/Sea \u2192 57.1%",
            "Definitely \u2192 14.3%",
            "",
            "\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500",
            "",
            "DG XIV Notes for upcoming dinner:",
            "Nominations: [Blank]",
            "Successes:",
            "Justin \u2014 AC coworker",
            "BJ \u2192 Ryan",
            "Cook \u2192",
            "[Unclear] \u2192 GQ William",
        ],
    },
    {
        "number": 19,
        "image": "IMG_4005.jpg",
        "title": "Nominations & Grievances Notes",
        "transcription": [
            "Nom\u2019s [Nominations]",
            "Phil 3/4 (Phil Rose, mentioned earlier).",
            "",
            "Grievances:",
            "John \u2014 pass \u2014 one point for giving pnu",
            "MM (Molinari) \u2014 pay.",
            "Nick \u2014 pay.",
            "Cook \u2014 text message.",
            "Ryan \u2014 inside joke quote",
            "Justin \u2014 emails from home",
        ],
    },
    {
        "number": 20,
        "image": "IMG_4006.jpg",
        "title": "DG XIII & DG XIV Recaps",
        "transcription": [
            "DG XIII",
            "DG: MR. CLIFFORD",
            "Date: 2/16/24",
            "Location: The Olympic Club Downtown",
            "",
            "STP:",
            "Dr. Cudahy \u2192 Huge Contract",
            "Justin \u2192 Cancer Free!",
            "Mr. Clifford \u2192 Big month at work",
            "PM: \u2014",
            "Grievances: WP \u2014 JM took tip away. BC: Hide your HY Doctor.",
            "",
            "\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500",
            "",
            "DG XIV",
            "DG: CPT Pritchett",
            "Date: 3/22 - Fri",
            "Location: The Marine Layer Club \u2192 The Golden Gate \u2192 The Bungalow - Tiburon",
            "STP: Johnny in a limo.",
            "Austin [Checked off]",
            "NOTES: (Sketch of a bearded man, likely CPT Pritchett).",
        ],
    },
    {
        "number": 21,
        "image": "IMG_4007.jpg",
        "title": "The DG Poem & DG XV",
        "transcription": [
            "Bungalow, the only place we go",
            "All together",
            "No one tells us no",
            "All for one",
            "And one for all",
            "Like the DG we roll",
            "Sharing our lives",
            "To the end we thrive",
            "Until the darkness falls",
            "We are together through all. \u2014 JM",
            "(Sketch of a muscular, flexing man).",
            "",
            "\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500",
            "",
            "DG XV Crab Feed III",
            "Host: MR. CLIFFORD",
            "Date: 4/26/24",
            "Successes/Grievances:",
            "Mr. Molinari: moved in w/ Nat in San. Might propose in next year?",
            "Mr. Hewitt: Megan\u2019s mom having a bone marrow transplant... got to see granddaughter in AZ. New project outside of Phoenix.",
            "Esq. Deming: 3rd annual Hawaii trip.",
            "Dr. Cudahy: Engagement party. Book cover. Ryan made website, Justin Built App. America\u2019s Best Doctors on Success TV.",
            "Mr. Rothaug: Playbook Day Club on Spotify.",
            "Mr. Molinari: Wedding planning 4/3/27. Chasing the Ponzi Home artwork.",
        ],
    },
    {
        "number": 22,
        "image": "IMG_4008.jpg",
        "title": "DG XVI \u2014 HOPR Night",
        "transcription": [
            "DG XVI",
            "HOPR NIGHT",
            "DG: DR. CUDAHY, MR. WHITE",
            "Date: 6/13/24",
            "Locations: The DG House \u2192 HOPR (House of Prime Rib)",
            "",
            "S/T/P:",
            "Wes: IPADs for leads",
            "John: New Job",
            "Justin: AI Built",
            'Ant: "Honeymoon train" (Post-wedding celebration).',
            "Ry: Houston job interview",
            "PM: None",
            "Grievances: Wes: Ry fumbled dinner. Cook: Johnny double date.",
        ],
    },
    {
        "number": 23,
        "image": "IMG_4009.jpg",
        "title": "DG XVIII \u2014 The Great Flower Fiasco",
        "transcription": [
            "DG XVIII",
            "Date: September 26, 2024",
            "Location: Starlight Room, Post Room, Dawn Club",
            "THE GREAT FLOWER FIASCO",
            "",
            "S/T/P:",
            "Evan: Job area expanding \u2014 boss baby. Megan is girlfriend.",
            "Johnny: work likes him, he likes them",
            "Cook: single and work sucks \u2192 expresses himself through invites",
            "Justin: work going bananas \u2192 TOP 8.0 AI company! AWS",
            "Ryan: no Houston job, no blackout",
            "Anthony: HAVING A BABY! (The big news of the night).",
            "Nick: crushed the presentation",
        ],
    },
    {
        "number": 24,
        "image": "IMG_4010.jpg",
        "title": "DG XVIII (cont.) & Festivus IX",
        "transcription": [
            "Wesley: didn\u2019t get job he wanted \u2192 laid off but okay.",
            "Proposal: add 9th since Wes can travel once per quarter \u2192 PASSED \u2192 be ready to discuss in Oct.",
            "",
            "Grievances:",
            "COOK \u2192 Ryan swindled w/ Mario\u2019s car, Ryan got 2 tickets \u2192 Punishment \u2192 Ryan to wash Cook\u2019s car by end of year.",
            "",
            "\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500",
            "",
            "FESTIVUS IX",
            "DG: MR. COOK",
            "Date: 12/19/25",
            "LOCATION(S): Trick Dog \u2014 White Elephant, FLOUR + WATER",
            "",
            "S/T/P:",
            "MR COOK \u2192 Manifest + Med Sales opportunities",
            "MR. WHITE: Proposal \u2192 career",
            "MR GREEN: layoff + DOGS \u2014 Barney",
            "MR. BROWN: Dating troubles \u2014 Career promotion + bonus. MUSIC on Spotify.",
        ],
    },
    {
        "number": 25,
        "image": "IMG_4011.jpg",
        "title": "Festivus IX (cont.) & Notes",
        "transcription": [
            "MR PINK | 4.75 \u2014 DC | Moves in w/ Natalie | JAN",
            "MR BLACK | Challenges w/ Judge",
            "",
            "GRIEVANCES",
            "MR PURPLE: MR EXECUTIVE \u2014 4k Acre expansion \u2014 Brazil Health woes + MR Purple assisting w/ maintenance",
            "MR YELLOW: Engagement!!!",
            "",
            "NOTES",
            "Crossword by MR. GREEN \u2192 #1",
            "White Elephant: LUBE! Rubicks!",
            "MR. COOK \u2192 $28 from Scratch off",
            "",
            "CADENCE:",
            "PROP 1: Quarterly",
            "PROP 2: Monthly",
            "PROP 3: Monthly w/ pitch (voted 3/5) \u2192 w/ Prep win",
            "VOTE: Prop",
        ],
    },
    {
        "number": 26,
        "image": "IMG_4012.jpg",
        "title": "Late Night Reflections",
        "transcription": [
            "After Flour & Water, we went to Benders (Dive bar in the Mission). I hate this shit and would rather be in the Marina. I am Tommy.",
            "",
            "Twas a great night, and many gifts were shared. Evan gave me a self portrait, which is the sexiest thing I\u2019ve ever seen in my life. I\u2019m a big fan, of me in action, so let\u2019s see some work.",
            "",
            "Who are down for action,",
            "(Written in giant, messy letters \u2014 likely an end-of-night rally cry).",
        ],
    },
    {
        "number": 27,
        "image": "IMG_4013.jpg",
        "title": "Memorable Moments \u2014 The Christmas Poem (Pt. 1)",
        "transcription": [
            "6) Memorable Moments",
            "",
            'CPT Pritchett\u2019s "The DG Christmas Poem"',
            "",
            "In San Francisco, where the lights twinkle bright",
            "A group of distinguished gents gather full of festive delight",
            "Distinguished they are, in their suits so divine",
            "Lets unwrap their tales in Christmas rhyme",
            "",
            "First, Mr White, the buddy daddy so sly,",
            "With a twinkle in his eye and mischief in his tie",
            "He\u2019s got a plan, on so grand",
            "To make Christmas the merriest in the land",
        ],
    },
    {
        "number": 28,
        "image": "IMG_4014.jpg",
        "title": "The Christmas Poem (Pt. 2)",
        "transcription": [
            "There\u2019s Mr Blue the Fashion King",
            "In suits and ties oh what bling",
            "With every step a runway he creates",
            "His style\u2019s unmatched, truly 1st rate.",
            "",
            "Next up is Mr Brown, a charming fellow",
            "Multiple girls under his umbrella",
            "In love + music, he\u2019s an artist a real connoisseur",
            "His heart\u2019s a dancefloor where love\u2019s the allure",
            "",
            "Now to Mr Purple and his bucket hats so chic",
            "In SF\u2019s for his trendsetting mystique",
            "With a hat for every mood and every twist",
            "In the city breeze his style can\u2019t be missed",
            "",
            "Look over there, it\u2019s Mr Orange so bold",
            "Broad shoulders and charm, never gets old",
            "A Giant among men w/ a heart so GRAND",
            "His presence alone can brighten the land",
        ],
    },
    {
        "number": 29,
        "image": "IMG_4015.jpg",
        "title": "Quotes",
        "transcription": [
            '"QUOTES"',
            "",
            '"Waggy Ribeye" \u2014 BC (Brian Cook likely meant "Wagyu").',
            '"Ahead of schedule" \u2014 RC (Ryan Cudahy).',
            '"It was not enough big" \u2014 WJP (Wesley Pritchett).',
            '"Nose Ring... One Crab" \u2014 Stranger.',
            '"Mistle Camelttoe" \u2014 Johnny.',
        ],
    },
    {
        "number": 30,
        "image": "IMG_4016.jpg",
        "title": "DG IV Extended Notes",
        "transcription": [
            "DG IV",
            "Justin looks like Matt Damon.",
            "Johnny\u2019s hair is getting long \u2192 looks like Giants baseball player.",
            "Notes for pre-drinks: legs are real.",
            "Dinner \u2192 Chotto Matte (The Nikkei restaurant in Union Square).",
            "Evan + Cook have \u201cshit room\u201d problem.",
            "Nick has a bad hip.",
            "Mario, Austin, Patrick on the table \u2192 no votes w/o Wes.",
            "Cook doesn\u2019t pay for March Madness but still wants money. Lol.",
        ],
    },
    {
        "number": 31,
        "image": "IMG_4017.jpg",
        "title": "DG XVI Trivia Night",
        "transcription": [
            "DG 16",
            "83 Proof \u2014 Trivia with Riddles",
            "Cook, John, De Monk",
            "missing Wes + EV",
            "At Tadich",
            "Mussels + Clams / Risotto",
            '"Whose style" \u2014 Ryan',
        ],
    },
    {
        "number": 32,
        "image": "IMG_4018.jpg",
        "title": "Goals & Positives",
        "transcription": [
            "(Business Card: Mr. Brian Cook)",
            "",
            "For next DG:",
            "Set goals",
            "Have a partner in crime",
            "Be better",
            "Discuss at August dinner",
            "Think about it",
            "Professional / Personal",
            "Johnny is an idiot.",
            "",
            "POSITIVES",
            "John \u2014 New job \u2014 going well, making new connections.",
            'NICO \u2014 "Say on Monday" \u2014 seeing chick next door.',
            'Justin \u2014 "Whole AI Company"',
            'RY \u2014 "MARA \u2192 40x \u2192 4.3k profit"',
            "Clifford \u2014 4th at 7th Fun",
            "Brian \u2014 what I like execs @ Google? \u2014 Ryan",
        ],
    },
    {
        "number": 33,
        "image": "IMG_4019.jpg",
        "title": "Member Updates & Stories",
        "transcription": [
            "Hasn\u2019t hit gout in 2 years",
            "Manager said he\u2019ll be ok, she\u2019s not hot",
            "Ryan NOT suffer health",
            "Cook Ex = Blonde + scummy",
            "Johnny Tsunami came to his dinner. Happy everyone came from Chicago.",
            "Is very wise. Nothing is new, nothing is old.",
            "Beach + Sangria",
            "",
            "Nick\u2019s mom was at a firm",
            'Ryan: UCSF transition \u2014 Switched EMR \u2014 "It was insane"',
            "$3 Grand more per month",
            "Kylie: Ryan\u2019s GF?",
            "Cookie: needs new housing, work shitty",
        ],
    },
    {
        "number": 34,
        "image": "IMG_4020.jpg",
        "title": "October 25 Nominations & Grievances",
        "transcription": [
            "Post-Dinner drinks \u2014 April Jean (A bar in North Beach).",
            "",
            "(Oct. 25 cont.)",
            "Nominations:",
            "Justin: Alex (marines)",
            "Nick/Ryan: Austin (TBD)",
            "Johnny: (Mickey)",
            "",
            "Grievances:",
            "Evan \u2014 nothing",
            "Justin \u2014 nothing",
            "Nick \u2014 nothing",
            "Ryan \u2014 zero",
            "Cook \u2014 zero",
            "Johnny \u2014 [took the brunt of the heat that night].",
        ],
    },
    {
        "number": 35,
        "image": "IMG_4021.jpg",
        "title": "DG XX \u2014 FESTIVUS III",
        "transcription": [
            "DG XX \u2014 FESTIVUS III",
            "Date: 12/19/24",
            "DG: CPT Pritchett / Mr. Green",
            "Locations: The Fairmont (Tonga Room?) \u2192 Acquerello (High-end Italian in Nob Hill)",
            "",
            "Successes, Trials, Promotions:",
            "JM: Job + career success",
            "EH: loss, next year will be great.",
            "JR: Launch \u2192 AI Avatar \u2192 Series A.",
            'BC: "Gnap" is like having a store in your pocket... living on own \u2192 work risks.',
            "ND: Great year \u2192 growth, perspective + App appreciation.",
            "AC: Appreciation of friendship + vulnerability. Health + happiness \u2192 Olympic Club softball.",
            "RC: LOVE + continued productivity w/ Gwen.",
            'WJP: NEW JOB!! Moving to Utah possibly? "Drones win the war" \u2014 purposeful job.',
        ],
    },
    {
        "number": 36,
        "image": "IMG_4022.jpg",
        "title": "Member Discussion & Charter Review",
        "transcription": [
            "Potential Member Discussion:",
            "MM \u2192 Y (Tally: 10)",
            "MW \u2192 N (Tally: 2)",
            "Mickey \u2192 INDUCTED",
            "Grievance of the Year: DR. CUDAHY",
            "",
            "Charter Review \u2014 FESTIVUS XX",
            "Mission/Charter: Consensus reached on adopting a greater cause/mission.",
            "Cadence: Vote needed \u2014 Monthly vs. Bi-monthly.",
            "Trip: Consensus reached.",
            "President: Consensus reached.",
            "Roles/Responsibilities (Dependent on cause/Trip).",
        ],
    },
    {
        "number": 37,
        "image": "IMG_4023.jpg",
        "title": "DG XXI \u2014 Olympic Club Crab Feed",
        "transcription": [
            "DG XXI \u2014 2/13/25",
            "Olympic Club Crab Feed ROUND II",
            "",
            "SUCCESSES:",
            "Dr. Cudahy \u2192 paying off Med Student Loans next month.",
            'Mr. Molinari \u2192 "Still Gay" (A classic DG recurring joke).',
            "Mr. Cook \u2192 New Apartment, Stryker Company doing Investor Relations.",
            "Mr. Meinhofer \u2192 New job at Bitcoin.",
            "Esq. Deming \u2192 1 week solo Hawaii trip. 14 hours on the beach. Sleep at 8.",
            "CPT. Pritchett \u2192 New job is great, lots of new hires. $40M Series A funding.",
            "Mr. Rothaug \u2192 Shifting his one bus to more education based. Working really hard w/ two companies.",
            "",
            "Grievances:",
            "Deming \u2192 CPT Pritchett leaving his \u201clady of the night\u201d in Esq\u2019s guest bed. GUILTY, no punishment.",
            "CPT Pritchett \u2192 Shit talking beer pong player, Johnny did nothing to shut him up.",
            "Mr. Clifford \u2192 Dr. Cudahy leaving Anthony + Bettini in the cold during CFP \u2192 PUNISHMENT \u2192 1 hour of Security Guard Duty at the Store.",
            "Dr. Cudahy \u2192 Mr. Cook Guilty of no-showing Super Bowl party \u2192 PUNISHMENT \u2192 Buy tickets to a Giants game.",
            'Mr. Molinari is Guilty of "A flavored can of Zyn\u2019s".',
        ],
    },
    {
        "number": 38,
        "image": "IMG_4024.jpg",
        "title": "Memorable Quotes & March Madness",
        "transcription": [
            "Emma Watson \u2014 Olivia / some scammery scam",
            "Rmm \u2014 GQ William pursuit",
            "Justin doesn\u2019t recognize Nicole Kidman (2025)",
            "Ryan got his ass kicked in Vegas by a woman",
            "",
            "DG X 11",
            "March Madness GAMS:",
            "Shuffleboard: Ryan wins after Cook cleared the sand.",
            "Pop-a-shot: Nick wins in an impassioned showdown.",
            "Shell: John wins in a Sherry showdown.",
            "Gong: Johnny wins in Sherry showdown.",
        ],
    },
    {
        "number": 39,
        "image": "IMG_4025.jpg",
        "title": "DG Dinner 06/25/25",
        "transcription": [
            "DG Dinner 06/25/25",
            "",
            "Anthony: baby life going well",
            "Ryan: making more money",
            "Mickey: Working a lot / side golf tourney",
            "Justin: Coming back from Europe",
            "Cook: work crazy",
            "Steve what a guy",
            "",
            "Ryan won over/under 1.5 hot chicks at Harry\u2019s",
            "Cook terrible take on Jets vs. 49ers",
            "HUGE back and forth Yanks vs. Giants. Really ever an agreement?",
            "27 Bro.",
            "Kickball squad getting back together?",
        ],
    },
    {
        "number": 40,
        "image": "IMG_4026.jpg",
        "title": "Quick Notes",
        "transcription": [
            "MR PINK \u2192 Drink",
            "DR CUDDY \u2192 SCC (Santa Clara County)",
            "MR MOLINARI \u2192 Drink lunch",
        ],
    },
    {
        "number": 41,
        "image": "IMG_4027.jpg",
        "title": "Beer Olympics",
        "transcription": [
            "CHAMPION",
            "BEER OLY (Beer Olympics)",
            "SEAN + BROS",
            "SOAKIN AND SING",
            "AMERICA!",
            "",
            "2 Penalty",
            "Tied Score",
        ],
    },
    {
        "number": 42,
        "image": "IMG_4028.jpg",
        "title": "DG XXV \u2014 Salt Lake City",
        "transcription": [
            "DG XXV",
            "DG: CPT Pritchett",
            "Date: 13 Sep \u201925 \u2192 SLC (Salt Lake City)",
            "LOC: SLC \u2192 WJP \u2192 CAPITOL lake \u2192 Spring",
            "STP: [Blank]",
            "PM: [Blank]",
            "GRIEVE (Grievance): DC (Dr. Cudahy)",
        ],
    },
]
